Layout/LineLength:
  Exclude:
    - "test/**/*"
  AllowedPatterns: ['\A\s*#']
Lint/EmptyBlock:
  Exclude:
    - "Appraisals"
Lint/StructNewOverride:
  Exclude:
    - "test/**/*"
Metrics/AbcSize:
  Exclude:
    - "test/**/*"
    - "lib/jeff.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "lib/peddler/client.rb"
    - "lib/mws/**/client.rb"
    - "test/**/*"
Metrics/ParameterLists:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/AccessorMethodName:
  Exclude:
    - "lib/mws/**/client.rb"
Naming/VariableNumber:
  Exclude:
    - "test/**/*"
Security/Eval:
  Enabled: false
Style/OpenStructUse:
  Exclude:
    - "test/**/*"
